site_name: Flywheels
site_url: https://www.stephenmwangi.com/flywheels/
site_author: Stephen Mwangi
site_description: >-
  Flywheels is an async-first Python web framework

repo_name: st3v3nmw/flywheels
repo_url: https://github.com/st3v3nmw/flywheels/
edit_uri: ""

theme:
    name: material
    logo: assets/favicon.ico
    favicon: assets/favicon.ico
    icon:
        repo: fontawesome/brands/github
    palette:
        - scheme: default
          toggle:
              icon: material/brightness-7
              name: Switch to dark mode
        - scheme: slate
          toggle:
              icon: material/brightness-4
              name: Switch to light mode
    features:
        - navigation.top
        - toc.follow

nav:
    - Index: index.md
    - Contributing: contributing.md
    - Changelog: changelog.md
    - License: license.md

plugins:
    - search

markdown_extensions:
    - toc:
          permalink: true
    - pymdownx.highlight:
          anchor_linenums: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - admonition
    - pymdownx.details
    - pymdownx.superfences
    - attr_list
    - footnotes
    - pymdownx.emoji:
          emoji_index: !!python/name:materialx.emoji.twemoji
          emoji_generator: !!python/name:materialx.emoji.to_svg

remote_branch: gh-pages
remote_name: origin
