name: Release

on:
  push:
    tags:
      - "*"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: >
          curl -sSL https://install.python-poetry.org | python3 -
          && poetry config virtualenvs.create false &&
          && poetry install --no-root

      - name: Publish to PyPI
        run: poetry publish --build
